/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckRouteImport } from './routes/check'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SaveRouteImport } from './routes/save'
import { Route as WSlugRouteImport } from './routes/w/$slug'
import { Route as WSlugIndexRouteImport } from './routes/w/$slug/index'
import { Route as WSlugExposureRouteImport } from './routes/w/$slug/exposure'
import { Route as WSlugMembersRouteImport } from './routes/w/$slug/members'
import { Route as WSlugSettingsRouteImport } from './routes/w/$slug/settings'
import { Route as WSlugExposureRunIdRouteImport } from './routes/w/$slug/exposure_.$runId'
import { Route as WSlugReportsReportIdRouteImport } from './routes/w/$slug/reports.$reportId'
import { Route as WSlugExposureRunIdObsIdRouteImport } from './routes/w/$slug/exposure_.$runId_.$obsId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SaveRoute = SaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugIndexRoute = WSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugExposureRoute = WSlugExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugMembersRoute = WSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSettingsRoute = WSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugExposureRunIdRoute = WSlugExposureRunIdRouteImport.update({
  id: '/exposure_/$runId',
  path: '/exposure/$runId',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugReportsReportIdRoute = WSlugReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugExposureRunIdObsIdRoute = WSlugExposureRunIdObsIdRouteImport.update({
  id: '/exposure_/$runId_/$obsId',
  path: '/exposure/$runId/$obsId',
  getParentRoute: () => WSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/save': typeof SaveRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/w/$slug/exposure': typeof WSlugExposureRoute
  '/w/$slug/members': typeof WSlugMembersRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/exposure/$runId': typeof WSlugExposureRunIdRoute
  '/w/$slug/reports/$reportId': typeof WSlugReportsReportIdRoute
  '/w/$slug/exposure/$runId/$obsId': typeof WSlugExposureRunIdObsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/save': typeof SaveRoute
  '/w/$slug/exposure': typeof WSlugExposureRoute
  '/w/$slug/members': typeof WSlugMembersRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug': typeof WSlugIndexRoute
  '/w/$slug/exposure/$runId': typeof WSlugExposureRunIdRoute
  '/w/$slug/reports/$reportId': typeof WSlugReportsReportIdRoute
  '/w/$slug/exposure/$runId/$obsId': typeof WSlugExposureRunIdObsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/save': typeof SaveRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/w/$slug/exposure': typeof WSlugExposureRoute
  '/w/$slug/members': typeof WSlugMembersRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/exposure_/$runId': typeof WSlugExposureRunIdRoute
  '/w/$slug/reports/$reportId': typeof WSlugReportsReportIdRoute
  '/w/$slug/exposure_/$runId_/$obsId': typeof WSlugExposureRunIdObsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check'
    | '/login'
    | '/onboarding'
    | '/save'
    | '/w/$slug'
    | '/w/$slug/exposure'
    | '/w/$slug/members'
    | '/w/$slug/settings'
    | '/w/$slug/'
    | '/w/$slug/exposure/$runId'
    | '/w/$slug/reports/$reportId'
    | '/w/$slug/exposure/$runId/$obsId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check'
    | '/login'
    | '/onboarding'
    | '/save'
    | '/w/$slug/exposure'
    | '/w/$slug/members'
    | '/w/$slug/settings'
    | '/w/$slug'
    | '/w/$slug/exposure/$runId'
    | '/w/$slug/reports/$reportId'
    | '/w/$slug/exposure/$runId/$obsId'
  id:
    | '__root__'
    | '/'
    | '/check'
    | '/login'
    | '/onboarding'
    | '/save'
    | '/w/$slug'
    | '/w/$slug/exposure'
    | '/w/$slug/members'
    | '/w/$slug/settings'
    | '/w/$slug/'
    | '/w/$slug/exposure_/$runId'
    | '/w/$slug/reports/$reportId'
    | '/w/$slug/exposure_/$runId_/$obsId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckRoute: typeof CheckRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SaveRoute: typeof SaveRoute
  WSlugRoute: typeof WSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/save': {
      id: '/save'
      path: '/save'
      fullPath: '/save'
      preLoaderRoute: typeof SaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/': {
      id: '/w/$slug/'
      path: '/'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof WSlugIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/exposure': {
      id: '/w/$slug/exposure'
      path: '/exposure'
      fullPath: '/w/$slug/exposure'
      preLoaderRoute: typeof WSlugExposureRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/members': {
      id: '/w/$slug/members'
      path: '/members'
      fullPath: '/w/$slug/members'
      preLoaderRoute: typeof WSlugMembersRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/settings': {
      id: '/w/$slug/settings'
      path: '/settings'
      fullPath: '/w/$slug/settings'
      preLoaderRoute: typeof WSlugSettingsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/exposure_/$runId': {
      id: '/w/$slug/exposure_/$runId'
      path: '/exposure/$runId'
      fullPath: '/w/$slug/exposure/$runId'
      preLoaderRoute: typeof WSlugExposureRunIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/reports/$reportId': {
      id: '/w/$slug/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/w/$slug/reports/$reportId'
      preLoaderRoute: typeof WSlugReportsReportIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/exposure_/$runId_/$obsId': {
      id: '/w/$slug/exposure_/$runId_/$obsId'
      path: '/exposure/$runId/$obsId'
      fullPath: '/w/$slug/exposure/$runId/$obsId'
      preLoaderRoute: typeof WSlugExposureRunIdObsIdRouteImport
      parentRoute: typeof WSlugRoute
    }
  }
}

interface WSlugRouteChildren {
  WSlugExposureRoute: typeof WSlugExposureRoute
  WSlugMembersRoute: typeof WSlugMembersRoute
  WSlugSettingsRoute: typeof WSlugSettingsRoute
  WSlugIndexRoute: typeof WSlugIndexRoute
  WSlugExposureRunIdRoute: typeof WSlugExposureRunIdRoute
  WSlugReportsReportIdRoute: typeof WSlugReportsReportIdRoute
  WSlugExposureRunIdObsIdRoute: typeof WSlugExposureRunIdObsIdRoute
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugExposureRoute: WSlugExposureRoute,
  WSlugMembersRoute: WSlugMembersRoute,
  WSlugSettingsRoute: WSlugSettingsRoute,
  WSlugIndexRoute: WSlugIndexRoute,
  WSlugExposureRunIdRoute: WSlugExposureRunIdRoute,
  WSlugReportsReportIdRoute: WSlugReportsReportIdRoute,
  WSlugExposureRunIdObsIdRoute: WSlugExposureRunIdObsIdRoute,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckRoute: CheckRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SaveRoute: SaveRoute,
  WSlugRoute: WSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
